### PR TITLE
Update amdgpu firmwares for Linux 5.11 DRM drivers

### PR DESCRIPTION
**Pull request by dumbbell**
The DRM drivers update is in freebsd/drm-kmod#163.

### CODE REVIEW

**Comment by evadot** [comment]
How was 20220509 chosen ?

**Comment by dumbbell** [comment]
I think that corresponds to the latest version at the time I started to work on 5.11.

**Comment by evadot** [comment]
> I think that corresponds to the latest version at the time I started to work on 5.11.

Ok :)
Do you have some amdgpu that works with 5.10 to test those firmware ?
There have been issues in the past when we updated the firmware and not drm-kmod. It's not a problem for intel firmware as they are versioned.

**Comment by dumbbell** [comment]
Yes, I have an older Radeon (I don't remember its name) which must work with 5.10. I can test it, not sure when.

**Comment by evadot** [comment]
> Yes, I have an older Radeon (I don't remember its name) which must work with 5.10. I can test it, not sure when.

Radeon or amdgpu ?

I'll try to test on a few machines here too to make sure there isn't any problems.

**Comment by dumbbell** [comment]
I will have to check which driver supports it.

**Comment by evadot** [comment]
I'll find some time next week when I'm back at home to test those firmware on my amd machine.

**Pull request merged**
